Add ribocounts dashboard data
naobservatory/mgs-pipeline pull request #22
Opened 2023-09-26 21:29 UTC by lennijusten

Ribocounts data added to dashboard files for Wu 2020, Bohl 2022, and Johnson 2023.

2023-09-26 21:31 UTC, lennijusten commented
Note the Johnson 2023 data as rRNA content of between 20-50%

2023-09-28 19:00 UTC, jeffkaufman requested changes
Did you forget to check in changes to `dashboard/prepare-dashboard-data.py`?

2023-09-28 19:01 UTC, jeffkaufman commented
Never mind; those changes are in https://github.com/naobservatory/mgs-pipeline/pull/21

2023-09-28 19:01 UTC, jeffkaufman approved these changes

2023-09-28 21:50 UTC, merged